version: "3.7"

services:
  app:
    build: ./
    tty: true
    ports:
      - 4001:3001
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh:delegated
    command: /bin/bash -c "chmod 600 ~/.ssh/id_rsa"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      # - mongodb_expressjs
      - mysql_expressjs
      - redis_expressjs
  # mongodb_expressjs:
  #   image: mongo:4.2.24-bionic
  #   volumes:
  #     - mongodb:/data
  #   environment:
  #     - TZ=Asia/Shanghai
  mysql_expressjs:
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d\charset.cnf:/etc/mysql/my.cnf
      - ./mysql/log:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
  redis_expressjs:
    image: redis:alpine
    command: [sh, -c, "redis-server --save \"\" --appendonly no"]
    ports:
      - 6379:6379
# volumes:
#   mongodb:
