version: "3.7"

services:
  app:
    build: ./
    ports:
      - 4001:3001
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Shanghai
  mongodb:
    image: mongo:4.2.24-bionic
    volumes:
      - mongodb:/data
    environment:
      - TZ=Asia/Shanghai

volumes:
  mongodb: